In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])             # 1-D array

array([1, 2, 3, 4, 5])

In [5]:
np.array([[1,2,3],[4,5,6],[7,8,9]])       #2-D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])        # 3-D array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
np.array([1,2,3], ndmin = 2)          # creates a 2-d array


array([[1, 2, 3]])

In [21]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr = np.array([(1,2,3),(4,5,6)] , dtype = [('a','<i4'),('b','<i8'),('c','<i2')])   # only i2,i4,i8 data type exists 

In [26]:
arr[0]

(1, 2, 3)

In [28]:
type(arr[0][1])

numpy.int64

In [8]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arrr = np.array([1,2,3], ndmin = 2)
arrr

array([[1, 2, 3]])

-0.0014315776532631344


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[0.0,
 0.017364817766693033,
 0.034729635533386066,
 0.0520944533000791,
 0.06945927106677213,
 0.08682408883346517,
 0.1041889066001582,
 0.12155372436685123,
 0.13891854213354426,
 0.15628335990023728]